enforce_dependencies: true
enforce_privacy: true
metadata:
  description: "Service catalog domain - handles service listings, categories, and vendor portfolios"
  protections:
    - 'prevent_this_package_from_violating_its_stated_dependencies'
    - 'prevent_other_packages_from_using_this_packages_internals'
dependencies:
  - "packs/user_management"